### ISSUE TITLE
Docker Containers are not able to resolve the node host name.

### ISSUE THREAD

**Issue by grohan2002** [mesosphere/mesos-dns#516]
DC/OS version - 1.10.3 
Deployment - AWS using cloud Formation template.
Tried Deploying a spark service - Failed 

Output from the private Node - 
nobody@ip-10-0-1-57:/etc$ ping $(hostname)
ping: unknown host ip-10-0-1-57.ec2.internal
nobody@ip-10-0-1-57:/etc$ 

Tried running it manually -

nobody@ip-10-0-1-57:/opt/spark/dist/bin$ ./spark-shell
Skipping bootstrap IP detection
spark-env: User: nobody
spark-env: No kerberos KDC config found
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
java.net.UnknownHostException: ip-10-0-1-57.ec2.internal: ip-10-0-1-57.ec2.internal: Name or service not known
  at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
  at org.apache.spark.util.Utils$.findLocalInetAddress(Utils.scala:891)
  at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress$lzycompute(Utils.scala:884)
  at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress(Utils.scala:884)
  at org.apache.spark.util.Utils$$anonfun$localHostName$1.apply(Utils.scala:941)
  at org.apache.spark.util.Utils$$anonfun$localHostName$1.apply(Utils.scala:941)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.util.Utils$.localHostName(Utils.scala:941)
  at org.apache.spark.internal.config.package$.<init>(package.scala:204)
  at org.apache.spark.internal.config.package$.<clinit>(package.scala)
  at org.apache.spark.SparkConf.validateSettings(SparkConf.scala:546)
  at org.apache.spark.SparkContext.<init>(SparkContext.scala:373)
  at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2516)
  at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:918)
  at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:910)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:910)
  at org.apache.spark.repl.Main$.createSparkSession(Main.scala:101)
  ... 47 elided

**Comment by jdef** [comment]
Thanks for the bug report. Did you try following the instructions in the
documentation?
https://docs.mesosphere.com/services/spark/2.1.0-2.2.1-1/spark-shell/

**Comment by grohan2002** [comment]
@jdef Putting the AWS DNS entry in the config.yaml and rebuilding the DC/OS environment resolved the issue.

**Comment by jdef** [comment]
Glad to hear it. I'll close this out then.
